export { default as Storefront } from './Storefront/Storefront'
export { default as Navbar } from './Navbar/Navbar'
export { default as Register } from './Register/Register'
export { default as Login } from './Login/Login'
export { default as Cart } from './Cart/Cart'
export { default as About } from './About/About'
export { default as Footer } from './Footer/Footer'
