# Generated by Django 4.1.3 on 2022-12-10 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StoreItem',
            fields=[
                ('item_name', models.CharField(max_length=220)),
                ('item_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('item_thumb_url', models.CharField(max_length=180)),
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
