# Generated by Django 4.1.3 on 2023-02-06 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_api', '0002_ratingdicty_remove_storeitem_item_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeitem',
            name='item_category',
            field=models.CharField(default='', max_length=454),
        ),
        migrations.AlterField(
            model_name='storeitem',
            name='item_description',
            field=models.CharField(default='', max_length=454),
        ),
        migrations.AlterField(
            model_name='storeitem',
            name='item_image_url',
            field=models.CharField(default='', max_length=454),
        ),
        migrations.AlterField(
            model_name='storeitem',
            name='item_title',
            field=models.CharField(default='', max_length=454),
        ),
    ]
