# Generated by Django 4.1.3 on 2023-02-06 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_api', '0003_alter_storeitem_item_category_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RatingDicty',
        ),
    ]
