# Generated by Django 4.1.3 on 2023-02-07 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_api', '0004_delete_ratingdicty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeitem',
            name='item_price',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='storeitem',
            name='item_rating',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=8),
        ),
    ]
